# ######################################################################################################
# ##                                                                                                  ##
# ##   AdvancementAnnouncer v${project.version} by Altkat(StreetMelodeez)                             ##
# ##   Discord: streetmelodeez                                                                        ##
# ##   Please use /aa reload to apply changes.                                                        ##
# ##   You can use /aa edit in game chat to edit this file.                                           ##
# ##                                                                                                  ##
# ######################################################################################################
#
# Custom Model Data Usage Examples:
#   custom-model-data: 123456 for direct integer.
#   custom-model-data: itemsadder:fire_sword for ItemsAdder.
#   custom-model-data: nexo:forest_sword for Nexo.
#
# Sound Usage:
# You can add a sound to any announcement.
# sound: "entity.player.levelup"
# A list of sounds can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# Leave "" for no sound.
#
# you can use placeholders from PlaceholderAPI in the messages. like %player_name%
# use | to print on a new line

presets:
  preset1:
    message: "&aThis is &6my cool| &amessage wow!"
    style: "GOAL"
    icon: "DIAMOND"
    custom-model-data: ""
    sound: ""
  store-preset:
    message: "&6You can get ranks|&6on our store &b/store"
    style: "TASK"
    icon: "EMERALD"
    custom-model-data: ""
    sound: ""
  discord-preset:
    message: "&9Join our discord server|&bdiscord.gg/yourdc"
    style: "CHALLENGE"
    icon: "BOOK"
    custom-model-data: ""
    sound: ""
  greeting:
    message: "&eHello &a%player_name%|&eHow is it going?"
    style: "GOAL"
    icon: "APPLE"
    custom-model-data: ""
    sound: ""


auto-announce:
  enabled: false    # should the plugin announce messages automatically
  interval: 30      # in seconds
  mode: "ORDERED"   # ORDERED, RANDOM
  messages:         # you can add as many messages as you want
    custommessage1:
      message: "&eHello &a%player_name%|&eHow is it going?"
      style: "GOAL"   # GOAL, TASK, CHALLENGE
      icon: "EMERALD" # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
      custom-model-data: ""
      sound: ""
    custommessage2:
      message: "&9Join our discord server|&bdiscord.gg/yourdc"
      style: "TASK"
      icon: "DIAMOND"
      custom-model-data: ""
      sound: ""
    vipmessage:
      message: "&6You can get ranks|&6on our store &b/store"
      style: "CHALLENGE"
      icon: "GOLD_INGOT"
      custom-model-data: ""
      sound: ""


# Messages to be displayed when players join the server.
# If you add more than one message, a random one will be selected and displayed.
join-features:
  join-messages:
    enabled: true
    messages:
      welcome-back-1:
        message: '&eWelcome back, &a%player_name%!'
        style: GOAL
        icon: GOLDEN_APPLE
        custom-model-data: ""
        sound: ""
      welcome-back-2:
        message: '&7[&a+&7] &f%player_name%'
        style: TASK
        icon: OAK_DOOR
        custom-model-data: ""
        sound: ""

  first-join-messages:
    enabled: true
    messages:
      first-join-1:
        message: '&dWelcome to the server, &b%player_name%!'
        style: CHALLENGE
        icon: CAKE
        custom-model-data: ""
        sound: ""
      first-join-2:
        message: '&b%player_name% &ejoined for the first time!'
        style: GOAL
        icon: TOTEM_OF_UNDYING
        custom-model-data: ""
        sound: ""



#These are the messages shown to players
#You can edit these messages
lang-messages:
  plugin-prefix: "&3[AdvancementAnnouncer] &r"
  config-reloaded: "&aConfig reloaded!"
  wrong-usage: "&cWrong usage! Please use /aa toggle"
  announcements-toggled-on: "&aYou now see the advancement announcements!"
  announcements-toggled-off: "&cYou no longer see the advancement announcements!"
  edit-gui-title: "&3Advancement Announcer Edit"
  presets-gui-title: "&3Advancement Announcer Presets"
  auto-announce-gui-title: "&3Auto Announce Config"
  input-cancelled: "&cInput process cancelled."