# ######################################################################################################
# ##                                                                                                  ##
# ##   AdvancementAnnouncer v${project.version} by Altkat(StreetMelodeez)                             ##
# ##   Discord: streetmelodeez                                                                        ##
# ##   Please use /aa reload to apply changes.                                                        ##
# ##   You can use /aa edit in game chat to edit this file.                                           ##
# ##                                                                                                  ##
# ######################################################################################################
#
# Custom Model Data Usage Examples:
#   custom-model-data: 123456 for direct integer.
#   custom-model-data: itemsadder:fire_sword for ItemsAdder.
#   custom-model-data: nexo:forest_sword for Nexo.
#
# ######################################################################################################
#
# Sound Usage:
#   You can add a sound to any announcement.
#   sound: "ENTITY_PLAYER_LEVELUP"
#   A list of sounds can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
#   Leave "" for no sound.
#   Recommendation: Use sounds with only TASK and GOAL types since CHALLENGE type has its own sound effect.
#
# ######################################################################################################
#
# Hex Color Usage:
#   This plugin supports Hex colors.
#   Use the format &#RRGGBB (e.g., &#FF0000) in any message.
#
# ######################################################################################################
#
# Auto-Announce & Message Options:
#   enabled: true/false - should the plugin announce messages automatically.
#   interval: in seconds - time between auto-announcements.
#   mode: "ORDERED" or "RANDOM" - the order of messages.
#   style: "GOAL", "TASK", or "CHALLENGE" - the frame style of the toast.
#   icon: Any valid Material name from Spigot.
#     (e.g., "DIAMOND", "GOLDEN_APPLE")
#     List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#
# ######################################################################################################
#
# Placeholder Usage:
#   You can use placeholders from PlaceholderAPI in the messages. like %player_name%
#
# ######################################################################################################
#
# How to print multiple lines:
#   Use | to print on a new line (If you print a one line message top line will be minecraft's default line (e.g, Goal Reached!)
#
# ######################################################################################################

presets:
  preset1:
    message: "&aThis is my &6cool|&amessage wow!"
    style: "GOAL"
    icon: "DIAMOND"
    custom-model-data: ""
    sound: "ENTITY_PLAYER_LEVELUP"
  store-preset:
    message: "&6You can get ranks|&6on our store &b/store"
    style: "TASK"
    icon: "EMERALD"
    custom-model-data: ""
    sound: ""
  discord-preset:
    message: "&9Join our discord server|&bdiscord.gg/yourdc"
    style: "CHALLENGE"
    icon: "BOOK"
    custom-model-data: ""
    sound: ""
  greeting:
    message: "&#54DAF4H&#54BBE5e&#549CD5l&#547DC6l&#545EB6o &e%player_name% &#54DAF4H&#54D2F0o&#54C9ECw
        &#54B9E3i&#54B1DFs &#54A0D7i&#5498D3t &#5487CBg&#547FC7o&#5477C2i&#546FBEn&#5466BAg&#545EB6?"
    style: GOAL
    icon: SUNFLOWER
    custom-model-data: ""
    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"


auto-announce:
  enabled: false
  interval: 30
  mode: "ORDERED"
  messages:
    custommessage:
      message: "&9Join our discord server|&bdiscord.gg/yourdc"
      style: "TASK"
      icon: "DIAMOND"
      custom-model-data: ""
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    vipmessage:
      message: "&6You can get ranks|&6on our store &b/store"
      style: "CHALLENGE"
      icon: "GOLD_INGOT"
      custom-model-data: ""
      sound: ""


# Messages to be displayed when players join the server.
# If you add more than one message, a random one will be selected and displayed.
join-features:
  join-messages:
    enabled: true
    messages:
      welcome-back-1:
        message: '&eWelcome back, &a%player_name%!'
        style: GOAL
        icon: GOLDEN_APPLE
        custom-model-data: ""
        sound: ""
      welcome-back-2:
        message: '&7[&a+&7] &f%player_name%'
        style: TASK
        icon: TOTEM_OF_UNDYING
        custom-model-data: ""
        sound: ""

  first-join-messages:
    enabled: true
    messages:
      first-join-1:
        message: '&dWelcome to the server, &b%player_name%!'
        style: CHALLENGE
        icon: CAKE
        custom-model-data: ""
        sound: ""
      first-join-2:
        message: '&b%player_name% &ejoined for the first time!'
        style: GOAL
        icon: TOTEM_OF_UNDYING
        custom-model-data: ""
        sound: ""



#These are the messages shown to players
#You can edit these messages
lang-messages:
  plugin-prefix: "&#7688FF[Advancement Announcer] &r"
  config-reloaded: "&#76FF90Config reloaded!"
  wrong-usage: "&#F86B6BWrong usage! Please use &e/aa toggle <announcements|sounds>"
  announcements-toggled-on: "&#76FF90You now see the advancement announcements!"
  announcements-toggled-off: "&#F86B6BYou no longer see the advancement announcements!"
  sounds-toggled-on: "&#76FF90Announcement sounds are now enabled!"
  sounds-toggled-off: "&#F86B6BAnnouncement sounds are now disabled!"
  no-permission: "&#F86B6BYou don't have permission to use this command."