# ######################################################################################################
# ##                                                                                                  ##
# ##   AdvancementAnnouncer v${project.version} by Altkat(StreetMelodeez)                                            ##
# ##   Discord: streetmelodeez                                                                        ##
# ##   Please use /aa reload to apply changes.                                                        ##
# ##   You can use /aa edit in game chat to edit this file.                                           ##
# ##                                                                                                  ##
# ######################################################################################################

# you can use placeholders from PlaceholderAPI in the messages. like %player_name%
# use | to print on a new line
presets: # you can add as many presets as you want
  preset1:
    message: "&aThis is &6my cool| &amessage wow!"
    style: "GOAL"
    icon: "DIAMOND"
  store-preset:
    message: "&6You can get ranks|&6on our store &b/store"
    style: "TASK"
    icon: "EMERALD"
  discord-preset:
    message: "&9Join our discord server|&bdiscord.gg/yourdc"
    style: "CHALLENGE"
    icon: "BOOK"
  greeting:
    message: "&eHello &a%player_name%|&eHow is it going?"
    style: "GOAL"
    icon: "APPLE"


auto-announce:
  enabled: false    # should the plugin announce messages automatically
  interval: 30      # in seconds
  mode: "ORDERED"   # ORDERED, RANDOM
  messages:         # you can add as many messages as you want
    custommessage1:
      message: "&eHello &a%player_name%|&eHow is it going?"
      style: "GOAL"   # GOAL, TASK, CHALLENGE
      icon: "EMERALD" # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    custommessage2:
      message: "&9Join our discord server|&bdiscord.gg/yourdc"
      style: "TASK"
      icon: "DIAMOND"
    vipmessage:
      message: "&6You can get ranks|&6on our store &b/store"
      style: "CHALLENGE"
      icon: "GOLD_INGOT"


# Messages to be displayed when players join the server.
# If you add more than one message, a random one will be selected and displayed.
join-features:
  join-messages:
    enabled: true
    messages:
      welcome-back-1:
        message: '&eWelcome back, &a%player_name%!'
        style: GOAL
        icon: GOLDEN_APPLE
      welcome-back-2:
        message: '&7[&a+&7] &f%player_name%'
        style: TASK
        icon: OAK_DOOR

  first-join-messages:
    enabled: true
    messages:
      first-join-1:
        message: '&dWelcome to the server, &b%player_name%!'
        style: CHALLENGE
        icon: CAKE
      first-join-2:
        message: '&b%player_name% &ejoined for the first time!'
        style: GOAL
        icon: TOTEM_OF_UNDYING



#These are the messages shown to players
#You can edit these messages
lang-messages:
  config-reloaded: "&3[AdvancementAnnouncer] &aConfig reloaded!"
  wrong-usage: "&cWrong usage! Please use /aa toggle"
  announcements-toggled-on: "&aYou now see the advancement announcements!"
  announcements-toggled-off: "&cYou no longer see the advancement announcements!"
  edit-gui-title: "&3Advancement Announcer Edit"
  presets-gui-title: "&3Advancement Announcer Presets"
  auto-announce-gui-title: "&3Auto Announce Config"
  input-cancelled: "&cInput process cancelled."